name: roaster
description: A platform where people can roast other people pictures.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  cloud_firestore:
  image_picker: ^0.6.0+2
  firebase_storage: ^7.0.0
  firebase_auth:
  google_sign_in: ^4.0.1+1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: ^2.0.2
  firebase_core: ^0.7.0
  path_provider: ^1.6.27
  firebase_messaging: ^4.0.0+1
  timeago: 2.0.17
  cached_network_image:
  flutter_svg:
  image_editor_pro: ^1.0.8
  flutter_cache_manager: ^2.1.1
  gallery_saver: ^2.0.3
  firebase_admob: ^0.11.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  fonts:
      - family: Signatra
        fonts:
          - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
